export const ADD_TODO = "ADD_TODO";
export const UPDATE_TOGGLE_TODO_STATUS = "UPDATE_TOGGLE_TODO_STATUS";
export const UPDATE_TOGGLE_TODO_TITLE = "UPDATE_TOGGLE_TODO_TITLE";
export const REMOVE_TODO = "REMOVE_TODO";
